Repository exida-Innovation/silstat-api-docs, pull requests merged in 2025-07, with the labels that each got.

#7 Events page
  docs/docs/tutorial-basics/authorization.md
  docs/docs/tutorial-basics/eventing.md
  docs/docs/tutorial-basics/eventing.mdx
  docs/docs/tutorial-basics/getting-started.md
  docs/docs/tutorial-basics/open-api.md
  docs/static/img/install-flow-diagram.png
Labels: documentation, enhancement

#12 [Chore] Initial CoPilot Instructions
  .github/copilot-instructions.md
  .github/workflows/copilot-setup-steps.yml
Labels: enhancement

#35 Update Authentication Entra instructions based on feedback
  docs/docs/tutorial-basics/authentication.mdx
Labels: documentation, enhancement

#38 Seperated database setting heading in table
  docs/docs/tutorial-basics/authorization.md
Labels: bug, documentation

#37 Bug/task 7169 fix landing page
  docs/docusaurus.config.js
  docs/src/components/HomepageFeatures/index.js
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/static/img/silstat-dashboard.jpg
  docs/static/img/silstat-data-collection.jpg
  docs/static/img/silstat-data-structure.jpg
  docs/static/img/silstat-digital-transformation.jpg
Labels: documentation

#39 Removed Analyze Role
  docs/docs/tutorial-basics/authorization.md
Labels: documentation, enhancement
